### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by os6sense** [solnic/mutant-examples#3]
I may be missing something simple but running on Ruby 2.2.0p0 results in:

/usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/lib/mutant/expression/parser.rb:28:in `call': Expression: "::Book#add_page" is not valid (Mutant::Expression::Parser::InvalidExpressionError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/lib/mutant/cli.rb:85:in `block in parse_match_expressions'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/lib/mutant/cli.rb:84:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/lib/mutant/cli.rb:84:in `parse_match_expressions'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/lib/mutant/cli.rb:69:in `parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/lib/mutant/cli.rb:38:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/procto-0.0.2/lib/procto.rb:62:in `block in initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/lib/mutant/cli.rb:22:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mutant-0.8.1/bin/mutant:35:in `<top (required)>'
	from /usr/local/bin/mutant:23:in `load'
	from /usr/local/bin/mutant:23:in `<main>'

It *may* be the instructions are unclear since the spec in the README doesn's exist in the master branch?

**Comment by mbj** [comment]
The examples in this repo are heavily outdated. I might refer you to mutants [readme](https://github.com/mutant#readme) that shows up-to-date examples.

**Comment by os6sense** [comment]
Cheers, I got things working ~ I was searching for a gentle introduction which I had assumed this to be; on the right track now.
